---
- name: 'Configuration Kiosk Mode'
  become: true
  hosts: localhost
  vars:
    USER: 'kiosk'
    KIOSK_URL: 'http://homepage.seahouse.local'

  tasks:
    - name: 'Preparing apt'
      apt:
        update_cache: yes
        upgrade: yes

    - name: 'Configuring raspi'
      import_tasks: raspi-config.yml 
      vars:
        BOOTBEHAVIOUR: "B2"
        LOCALE: "it_IT.UTF-8"
        TIMEZONE: "Europe/Rome"
        XKBLAYOUT: "it"
  
    - name: 'Installing Requirements'
      apt:
        name: 
          - xserver-xorg
          - x11-xserver-utils
          - xinit
          - openbox
          - chromium-browser
  
    - name: 'Configuring autostart'
      blockinfile:
        path: '/etc/xdg/openbox/autostart'
        block: |
          xset -dpms
          xset s noblank
          xset s off
          chromium-browser  --noerrdialogs --disable-infobars --kiosk $KIOSK_URL
    
    - name: 'Configuring environment'
      lineinfile: 
        path: '/etc/xdg/openbox/environment'
        line: 'export KIOSK_URL={{ KIOSK_URL }}'
    
    - name: 'Start X'
      lineinfile: 
        path: '/home/{{ USER }}/.bashrc'
        line: '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx -- -nocursor'
  
    - name: 'Reboot'
      reboot:
