---
- name: Get boot autologin
  shell: "raspi-config nonint get_autologin"
  register: auto_login
  changed_when: False

- name: Print boot autologin status
  debug: 
    msg: "Boot autologin is: {{ auto_login.stdout }}"

- name: Set Boot behaviour
  shell: "raspi-config nonint do_boot_behaviour {{ BOOTBEHAVIOUR }}"

- name: Change locale
  shell: "raspi-config nonint do_change_locale {{ LOCALE }}"

- name: Change timezone
  shell: "raspi-config nonint do_change_timezone {{ TIMEZONE }}"

- name: Change keyboard layout
  shell: "raspi-config nonint do_configure_keyboard {{ XKBLAYOUT }}"
