---
- name: "Debian Configuration"
  become: yes
  hosts: localhost
  vars_file:
    - path.yml
  
  ##############################################################################
  # DEFINE ALL TASKS TO LAUNCH
  ##############################################################################
  tasks:  
    - import_tasks: "{{PLAYBOOKS}}/package.yml"
    - import_tasks: "{{PLAYBOOKS_DOCKER}}/setup.yml"
